# Use postgres/example user/password credentials
version: '3.9'

services:
  db_dev:
    image: postgres
    container_name: pg_dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  db_test:
    image: postgres
    container_name: pg_test
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}